apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    app: myapp
    type: front-end
  name: myapp-rc
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        app: nginx-app
        name: nginx-pod
    spec: 
      containers: 
        - image: nginx
          name: nginx
